In [2]:
import numpy as np
import pandas as pd
import spacy
nlp=spacy.load("en_core_web_sm")

In [3]:
df=pd.read_csv("sentiment_analysis.csv")

In [4]:
df.head()

Year  Month  Day Time of Tweet  \
0  2018      8   18       morning   
1  2018      8   18          noon   
2  2017      8   18         night   
3  2022      6    8       morning   
4  2022      6    8          noon   

                                                text sentiment     Platform  
0              What a great day!!! Looks like dream.  positive    Twitter    
1     I feel sorry, I miss you here in the sea beach  positive    Facebook   
2                                     Don't angry me  negative     Facebook  
3  We attend in the class just for listening teac...  negative    Facebook   
4                  Those who want to go, let them go  negative   Instagram

In [5]:
df.sentiment.value_counts()

sentiment
neutral     199
positive    166
negative    134
Name: count, dtype: int64

In [6]:
df.shape

(499, 7)

In [7]:
min_set=134

In [8]:
df_positive=df[df.sentiment=="positive"].sample(min_set,random_state=2022)
df_negative=df[df.sentiment=="negative"].sample(min_set,random_state=2022)
df_netural=df[df.sentiment=="neutral"].sample(min_set,random_state=2022)

In [9]:
df_netural

Year  Month  Day Time of Tweet  \
143  2023      2   24       morning   
58   2023      9   14       morning   
256  2023      7    9          noon   
88   2019      3    2          noon   
298  2019      8   20          noon   
..    ...    ...  ...           ...   
271  2018     12   10          noon   
324  2023      1   28       morning   
238  2023      2   28          noon   
150  2021     11   29          noon   
253  2023      6    9          noon   

                                                  text sentiment     Platform  
143             Always have wanted to go to university   neutral    Twitter    
58     Grabbing coffee from  then making mom breakfast   neutral    Facebook   
256                           Sigh... you know I am...   neutral     Twitter   
88   is cleaning the house for her family who is co...   neutral   Instagram   
298   Morning! If I get to see it, I`ll let you kno...   neutral     Twitter   
..                                                 ...       ...          ...  
271                                           i know!!   neutral     Twitter   
324   Not sure it didn`t say it was 2 big. I jst sa...   neutral    Facebook   
238                                                Thx   neutral   Instagram   
150   was that sass I detect?  As long as it isn`t ...   neutral   Instagram   
253  Waiting for tish to get off. Got to drive my m...   neutral     Twitter   

[134 rows x 7 columns]

In [10]:
df_positive

Year  Month  Day Time of Tweet  \
344  2019      7   28         night   
388  2021     12    8          noon   
436  2023      2   15          noon   
220  2016      2   28          noon   
278  2020      1    5         night   
..    ...    ...  ...           ...   
123  2017     12    1          noon   
151  2021      2   10         night   
217  2017     12    1          noon   
39   2018     11    5       morning   
273  2023      6    7       morning   

                                                  text sentiment     Platform  
344                                     oh nice going!  positive   Instagram   
388   Thanks for the warm welcome! We didn`t make p...  positive   Instagram   
436  loves her mum very much! Happy Mothers Day to ...  positive    Twitter    
220  Errors are red but my life is blue, I love ros...  positive    Twitter    
278                                             Thanks  positive   Instagram   
..                                                 ...       ...          ...  
123                         Feeling smooth like chrome  positive    Twitter    
151              yeah I was thinking about that ,ahaha  positive    Facebook   
217                         Feeling smooth like chrome  positive    Twitter    
39                               romance zero is funny  positive    Facebook   
273  Went to a party last night. Dindin and I showe...  positive    Facebook   

[134 rows x 7 columns]

In [15]:
df_negative

Year  Month  Day Time of Tweet  \
15   2017     11    5       morning   
311  2023      8   18         night   
492  2023      1   27       morning   
323  2023      1   25         night   
69   2022      6    8       morning   
..    ...    ...  ...           ...   
81   2017     11    5       morning   
56   2020     11   29          noon   
369  2022      7   17       morning   
454  2019     10    8          noon   
484  2018     11    7          noon   

                                                  text sentiment     Platform  
15                                   Don't distrube me  negative    Facebook   
311                                   Ship. I`m stuck.  negative   Instagram   
492                  Sorry, we`ll try to keep it down.  negative    Facebook   
323   u think u have bills Ha!Ii just finished payi...  negative   Instagram   
69   We attend in the class just for listening teac...  negative    Facebook   
..                                                 ...       ...          ...  
81                                   Don't distrube me  negative    Facebook   
56           I have bad headech, what I need to do now  negative    Twitter    
369       l`m on 3 days too matt. No fun this weekend.  negative    Facebook   
454                                      Still jealous  negative     Twitter   
484                                    Hicks are mean!  negative   Instagram   

[134 rows x 7 columns]

In [11]:
df_balanced=pd.concat([df_positive,df_negative,df_netural])

In [12]:
df_balanced.head()

Year  Month  Day Time of Tweet  \
344  2019      7   28         night   
388  2021     12    8          noon   
436  2023      2   15          noon   
220  2016      2   28          noon   
278  2020      1    5         night   

                                                  text sentiment     Platform  
344                                     oh nice going!  positive   Instagram   
388   Thanks for the warm welcome! We didn`t make p...  positive   Instagram   
436  loves her mum very much! Happy Mothers Day to ...  positive    Twitter    
220  Errors are red but my life is blue, I love ros...  positive    Twitter    
278                                             Thanks  positive   Instagram

In [13]:
df_balanced.shape

(402, 7)

In [14]:
df_balanced.sentiment.value_counts()

sentiment
positive    134
negative    134
neutral     134
Name: count, dtype: int64

In [15]:
df_balanced.describe()

Year       Month         Day
count   402.000000  402.000000  402.000000
mean   2020.363184    6.084577   15.771144
std       2.863031    3.657781    8.842335
min    2010.000000    1.000000    1.000000
25%    2018.250000    2.000000    8.000000
50%    2021.000000    6.000000   16.000000
75%    2023.000000    9.000000   22.750000
max    2023.000000   12.000000   31.000000

In [16]:
df_balanced.head()

Year  Month  Day Time of Tweet  \
344  2019      7   28         night   
388  2021     12    8          noon   
436  2023      2   15          noon   
220  2016      2   28          noon   
278  2020      1    5         night   

                                                  text sentiment     Platform  
344                                     oh nice going!  positive   Instagram   
388   Thanks for the warm welcome! We didn`t make p...  positive   Instagram   
436  loves her mum very much! Happy Mothers Day to ...  positive    Twitter    
220  Errors are red but my life is blue, I love ros...  positive    Twitter    
278                                             Thanks  positive   Instagram

In [17]:
df_balanced.head()

Year  Month  Day Time of Tweet  \
344  2019      7   28         night   
388  2021     12    8          noon   
436  2023      2   15          noon   
220  2016      2   28          noon   
278  2020      1    5         night   

                                                  text sentiment     Platform  
344                                     oh nice going!  positive   Instagram   
388   Thanks for the warm welcome! We didn`t make p...  positive   Instagram   
436  loves her mum very much! Happy Mothers Day to ...  positive    Twitter    
220  Errors are red but my life is blue, I love ros...  positive    Twitter    
278                                             Thanks  positive   Instagram

In [18]:
df_new=df_balanced.drop(['Day','Time of Tweet','Platform','Year','Month','Day'],axis=1)

In [19]:
df_balanced.head()

Year  Month  Day Time of Tweet  \
344  2019      7   28         night   
388  2021     12    8          noon   
436  2023      2   15          noon   
220  2016      2   28          noon   
278  2020      1    5         night   

                                                  text sentiment     Platform  
344                                     oh nice going!  positive   Instagram   
388   Thanks for the warm welcome! We didn`t make p...  positive   Instagram   
436  loves her mum very much! Happy Mothers Day to ...  positive    Twitter    
220  Errors are red but my life is blue, I love ros...  positive    Twitter    
278                                             Thanks  positive   Instagram

In [20]:
df_new.head()
df_new.sentiment.value_counts()

sentiment
positive    134
negative    134
neutral     134
Name: count, dtype: int64

In [23]:
df_new['label']=df_new.sentiment.map({
    "positive":0,
    "negative":1,
    "neutral":2
}
                                   )

In [24]:
df_new.head()

text sentiment  label
344                                     oh nice going!  positive      0
388   Thanks for the warm welcome! We didn`t make p...  positive      0
436  loves her mum very much! Happy Mothers Day to ...  positive      0
220  Errors are red but my life is blue, I love ros...  positive      0
278                                             Thanks  positive      0

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer(ngram_range=(1,2))

In [60]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df_new.text,df_new.label,test_size=0.2,random_state=2022,stratify=df_new.label)

In [62]:
x_train

328                                               There!
175                                           Hell Yeah!
205      Grabbing coffee from  then making mom breakfast
19           I will never fall in love until I found you
355     ohoh i missed all ur tweets  im gonna have to...
                             ...                        
450    concert tonight  chackin out and not coming to...
51     should be sleeping.  lost my voice a couple da...
80         Always somewhere I miss you where I have been
218    Errors are red but my life is looks like blue ...
270     HIM shirt at dinner? Do you need to ask??  Do...
Name: text, Length: 321, dtype: object

In [63]:
x_test

296           what`s goin on hun?  I`m worried about you
282    Felt like ****, behaved like my son; ate to co...
444                                      Morning tweeple
131                                  failed inspection. 
429    'my name is Tony!!!!!! ...not hey!!!!' -  poor...
                             ...                        
231    Screw the reviews, I thought Wolverine was awe...
24                      Follow me, I will follow you too
17                 i`ve been sick for the past few days 
403         I wish I could get my nails done  stupid job
356     Damnit all. That sucks.  You were one of the ...
Name: text, Length: 81, dtype: object

In [64]:
y_train

328    2
175    2
205    2
19     0
355    1
      ..
450    2
51     1
80     2
218    1
270    2
Name: label, Length: 321, dtype: int64

In [65]:
y_test

296    1
282    1
444    0
131    1
429    1
      ..
231    0
24     2
17     2
403    1
356    1
Name: label, Length: 81, dtype: int64

In [66]:
x_train_v=v.fit_transform(x_train)

In [68]:
x_train_v.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

MultinomialNB()

In [70]:
x_test_v=v.transform(x_test)

In [71]:
x_pred=model.predict(x_test_v)

In [72]:
from sklearn.metrics import classification_report
print(classification_report(x_pred,y_test))

              precision    recall  f1-score   support

           0       0.89      0.80      0.84        30
           1       0.81      0.76      0.79        29
           2       0.67      0.82      0.73        22

    accuracy                           0.79        81
   macro avg       0.79      0.79      0.79        81
weighted avg       0.80      0.79      0.79        81



In [73]:
x_pred

array([1, 1, 0, 1, 1, 2, 2, 0, 1, 2, 1, 1, 0, 1, 2, 0, 1, 2, 0, 0, 1, 2,
       0, 1, 0, 2, 1, 0, 1, 0, 2, 0, 1, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 0,
       1, 0, 1, 1, 0, 0, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 1, 2, 0, 0, 1, 1,
       0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 0, 2, 0, 1], dtype=int64)

In [80]:
positive=["This product was a huge disappointment. It didn't work as advertised and was a waste of money.", "Terrible experience with customer service. They were unresponsive and rude.", "I regret buying this item. Poor quality and it broke after just a few uses."]
positive_v=v.transform(positive)

In [81]:
model.predict(positive_v)

array([2, 2, 1], dtype=int64)